version: '3.8'

services:
  app:
    image: chatbot-v.3.1.2
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/cb
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: awang
      POSTGRES_PASSWORD: wdefaulsj
      POSTGRES_DB: database_name
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:
    cb

networks:
  app-network:
    cb
